name: Node.js CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install -g yarn
      - run: yarn
      - run: yarn test

  build-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup Node.js v16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install and build
        run: |
          yarn
          cd packages/abi-to-sol
          yarn prepare
          cd ../web-ui
          PUBLIC_URL=https://gnidan.github.io/abi-to-sol/ yarn build
