name: Deploy Web UI
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup Node.js v16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install and build
        run: |
          yarn
          cd packages/abi-to-sol
          yarn prepare
          cd ../web-ui
          PUBLIC_URL=https://gnidan.github.io/abi-to-sol/ yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: packages/web-ui/build

